//
//  CTPersistanceQueryCommand+DataManipulations.h
//  CTPersistance
//
//  Created by casa on 15/10/5.
//  Copyright © 2015年 casa. All rights reserved.
//

#import "CTPersistanceQueryCommand.h"

@interface CTPersistanceQueryCommand (DataManipulations)

/**
 *  insert table with table name and data list
 *
 *  You should never use this method directly, use insert methods in CTPersistanceTable instead
 *
 *  @param tableName table name
 *  @param dataList  data list to insert
 *
 *  @return return CTPersistanceQueryCommand
 *
 *  @warning You should never use this method directly, use insert methods in CTPersistanceTable instead
 *
 */
- (CTPersistanceQueryCommand *)insertTable:(NSString *)tableName columnInfo:(NSDictionary *)columnInfo dataList:(NSArray *)dataList error:(NSError *__autoreleasing *)error;

/**
 *  update table with data and condition with condition params.
 *
 *  You should never use this method directly, use update methods in CTPersistanceTable instead
 *
 *  @param tableName        table name
 *  @param valueString      string like "columnName = value", or "columnName = :value" and the bindValueList should contain the invocation to bind :value.
 *  @param whereString      string like "columnName = value", or "columnName = :value" and the bindValueList should contain the invocation to bind :value. this string will append after "WHERE" in SQL.
 *  @param bindValueList    this is a invocation array which indicates the :value and the real value, which will be bind into the SQL. generated by the category: NSMutableArray+CTPersistanceBindValue.h
 *  @param error            error
 *
 *  @return return CTPersistanceQueryCommand
 *
 *  @warning You should never use this method directly, use insert methods in CTPersistanceTable instead
 *
 */
- (CTPersistanceQueryCommand *)updateTable:(NSString *)tableName valueString:(NSString *)valueString whereString:(NSString *)whereString bindValueList:(NSArray <NSInvocation *> *)bindValueList error:(NSError * __autoreleasing *)error;

/**
 *  delete table with table name and condition with conditition params
 *
 *  You should never use this method directly, use update methods in CTPersistanceTable instead
 *
 *  @param tableName        table name
 *  @param whereString      string like "columnName = value", or "columnName = :value" and the bindValueList should contain the invocation to bind :value. this string will append after "WHERE" in SQL.
 *  @param bindValueList    this is a invocation array which indicates the :value and the real value, which will be bind into the SQL. generated by the category: NSMutableArray+CTPersistanceBindValue.h
 *  @param error            error
 *
 *  @return return CTPersistanceQueryCommand
 *
 *  @warning You should never use this method directly, use insert methods in CTPersistanceTable instead
 *
 */
- (CTPersistanceQueryCommand *)deleteTable:(NSString *)tableName whereString:(NSString *)whereString bindValueList:(NSArray <NSInvocation *> *)bindValueList error:(NSError * __autoreleasing *)error;

- (CTPersistanceQueryCommand *)truncateTable:(NSString *)tableName;

@end
