//
//  CTPersistanceQueryBuilder.h
//  CTPersistance
//
//  Created by casa on 15/10/5.
//  Copyright © 2015年 casa. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "CTPersistanceDataBase.h"
#import <sqlite3.h>
#import "CTPersistanceSqlStatement.h"

/**
 *  CTPersistanceQueryCommand is a SQL builder for CTPersistance
 *
 *  @warning you should never create your own instance of CTPersistanceQueryCommand
 *
 */
@interface CTPersistanceQueryCommand : NSObject

/**
 *  related CTPersistanceDataBase
 */
@property (nonatomic, weak, readonly) CTPersistanceDataBase *database;

/**
 *  create CTPersistanceQueryCommand with name of database
 *
 *  @param databaseName the name of database
 *
 *  @return return CTPersistanceQueryCommand
 *
 *  @warning You should never use this method directly, use insert methods in CTPersistanceTable instead
 *
 */
- (instancetype)initWithDatabaseName:(NSString *)databaseName swiftModuleName:(NSString *)swiftModuleName;

/**
 *  create CTPersistanceQueryCommand with instance of CTPersistanceDataBase
 *
 *  @param database the CTPersistanceDataBase instance
 *
 *  @return return CTPersistanceQueryCommand
 *
 *  @warning You should never use this method directly, use insert methods in CTPersistanceTable instead
 *
 */
- (instancetype)initWithDatabase:(CTPersistanceDataBase *)database;



/**
 *  compile sql string for future use
 *
 *  @param sqlString        sql string to compile
 *  @param bindValueList    the values bind to the sql string, generated by NSMutableArray+CTPersistanceBindValue.h : addBindKey:bindValue:columnDescription:;
 *  @param error            error if fails
 *
 *  @return return fetched data list
 *
 */
- (CTPersistanceSqlStatement *)compileSqlString:(NSString *)sqlString bindValueList:(NSMutableArray <NSInvocation *> *)bindValueList error:(NSError **)error;

@end
